### ISSUE TITLE
README has a reference to a .env file that doesn't seem to exist

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/vr2gather-orchestrator-v2#11]
Subject says all

**Comment by jackjansen** [comment]
Turns out this isn't a documentation issue but a bug. The `.env-sample` file is missing, but if I ignore that fact then `yarn start` fails. Here's the first few lines of the output:

```
jack@beignet vr2gather-orchestrator-v2 % yarn start
yarn run v1.22.22
$ node --enable-source-maps bin/build.js
webpack://vr2gather-orchestrator/util.ts:46
        throw new Error(`Environment has no key ${k}`);
        ^


Error: Environment has no key LOG_LEVEL

```

Creating a file `.env` with the following content seems to work:
```
PORT=8090
LOG_LEVEL=debug
```

**Comment by troeggla** [comment]
This is strange, the `.env-sample` file is here: https://github.com/cwi-dis/vr2gather-orchestrator-v2/blob/master/.env-sample

The crash upon a missing `.env` is intended since the application cannot start without the configuration values inside of it and I don't like checking environment variables into repositories.
