### ISSUE TITLE
Version 1.25.5 required for `docker-compose`

### ISSUE THREAD

**Issue by jvdrhoof** [cwi-dis/vr2gather-orchestrator-v2#9]
To support version 3.8, `docker-compose` version 1.25.5 or higher is required (see https://stackoverflow.com/questions/61344927/when-using-docker-compose-3-8-getting-version-is-unsupported-error). It is recommended to mention this in the README, since Ubuntu 22.04LTS currently provides version 1.25.0 when installing `docker-compose` through `apt`.

**Comment by troeggla** [comment]
Thanks for the report! I've removed the version declaration from `docker-compose.yml` altogether, since it seems to be deprecated in newer versions anyway and it increases the chance for older versions of `compose` to work.

I've also added a note to the README that Ubuntu users should consider downloading their Docker from the official Docker APT repository to get the latest version.
